### ISSUE TITLE
location of config yam files

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/management#1]
fir this one its better to have config files in

~/.cloudmesh/accounts

**Comment by avaradha** [comment]
Will look into this one shortly...

**Comment by laszewsk** [comment]
currently:
cp etc/accounts/cloudmesh_user.yaml ~/.cloudmesh/cloudmesh_user.yaml
cp etc/accounts/cloudmesh_project.yaml ~/.cloudmesh/cloudmesh_project.yaml
python setup.py install

this should be in ~/.cloudmesh/accounts

There should also not be a reason to copy these files by hand, as this should be auto generated.

however it needs to be documented how to modify them, so maybe we need

python setup.py yaml
cd ...
edit this and that, make mods here an there
python setup.py install

However if you are satisfied with the current objects you do not have to modify anything and you should just use

python setup.py install

**Comment by laszewsk** [comment]
I just saw that you correct used etc/...../accounts but you do not push that dir out into .cloudmesh

i thus suggest you use to accounts rather than management ...

**Comment by avaradha** [comment]
1. Added a small section about the structure of a field description in the yaml file. 
2. Amended the SetupYaml class in setup.py to copy the files from etc/accounts to "~/.cloudmesh/accounts"
3. Added a ResetYaml class in setup.py to use when the yaml files needs to be replaced
4. Added a ReGenFile class in setup.py to regenerate the python files base_user.py and base_project.py under cloudmesh_management directory.
