### ISSUE TITLE
Documentation of how to create and modify the input object as time of generation

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/management#4]
I am not sure if this is documented:

how to create and modify the input object as time of generation

**Comment by avaradha** [comment]
Can you elaborate on this one? 
At the moment, if you do random user generation, an User Object is created and populated with random values and then stored in mongo. 

The same approach is followed when the user is created from yaml file. The yaml file read and the read configuration details are added to an User Object. This User object is then stored in mongo.

Is this what you are looking for or something different?

**Comment by laszewsk** [comment]
the input we have has some object.

```
eg. firstname: StringField or so
```

what we need is to document how to change that. Maybe I overlooked. but i think this must be promimnently featured ...

**Comment by avaradha** [comment]
The instructions on how to add or amend the fields is provided under the section: "How to add/amend fields to the YAML file" in the README.rst file.
